// script.js

// --- 1. SEO & METADATA MANAGEMENT ---
function updateSEO(lang) {
    const title = resumeData.ui.documentTitle[lang];
    const desc = resumeData.ui.seoDesc[lang];
    const jobTitle = resumeData.ui.jobTitleShort[lang];

    // Update Title & Meta
    document.title = title;
    document.querySelector('meta[name="description"]').setAttribute('content', desc);
    document.querySelector('meta[property="og:title"]').setAttribute('content', title);
    document.querySelector('meta[property="og:description"]').setAttribute('content', desc);
    document.querySelector('meta[name="twitter:title"]').setAttribute('content', title);
    document.querySelector('meta[name="twitter:description"]').setAttribute('content', desc);

    // Update JSON-LD
    try {
        const jsonLdScript = document.getElementById('json-ld');
        if (jsonLdScript) {
            const schema = JSON.parse(jsonLdScript.textContent);
            schema.jobTitle = jobTitle;
            schema.description = desc;
            jsonLdScript.textContent = JSON.stringify(schema, null, 2);
        }
    } catch (e) { console.warn("JSON-LD update failed", e); }
}

// --- 2. MAIN RENDER FUNCTION ---
function renderResume(lang) {
    updateSEO(lang);
    document.documentElement.lang = lang;

    // 1. HEADER (Static IDs)
    document.getElementById('p-name').textContent = resumeData.profile.name;
    document.getElementById('p-title').textContent = resumeData.profile.title[lang];
    document.getElementById('p-location').textContent = resumeData.meta.location[lang];
    
    const mailLink = document.getElementById('link-email');
    mailLink.textContent = resumeData.meta.email;
    mailLink.href = `mailto:${resumeData.meta.email}`;

    const linkedinLink = document.getElementById('link-linkedin');
    linkedinLink.textContent = resumeData.meta.linkedinLabel;
    linkedinLink.href = resumeData.meta.linkedin;
    
    // PDF Button
    const printBtn = document.getElementById('ui-print');
    if(printBtn) printBtn.textContent = resumeData.ui.print[lang];

    // 2. MAIN CONTENT (Dynamic Generation)
    // Uses utils.js to rebuild the <main> tag content
    const mainHTML = resumeUtils.renderLayout(resumeData, lang);
    const mainContent = document.getElementById('main-content');
    mainContent.innerHTML = mainHTML;

    // 3. AUTOMATED SECTION ANIMATIONS
    // Finds all sections and applies a staggered delay automatically
    const sections = mainContent.querySelectorAll('section');
    sections.forEach((section, index) => {
        section.style.opacity = "0"; // Initial state for animation
        section.style.animation = `slideUp 0.6s ease-out ${(index + 1) * 0.1}s forwards`;
    });

    // 4. STATES & UI ANIMATION
    document.getElementById('btn-tr').setAttribute('aria-pressed', lang === 'tr');
    document.getElementById('btn-en').setAttribute('aria-pressed', lang === 'en');
    
    // Staggered animation for skill tags
    const skillTags = document.querySelectorAll('.skill-tag');
    skillTags.forEach((tag, index) => { 
        tag.style.animationDelay = `${(index + 1) * 0.05}s`; 
    });
    
    document.body.classList.remove('lang-tr', 'lang-en');
    document.body.classList.add(`lang-${lang}`);
}

// --- 3. SKILL NAVIGATION LOGIC (NEW) ---
function setupSkillNavigation() {
    // A. Close dropdowns when clicking outside
    document.addEventListener('click', (e) => {
        const existingDropdown = document.querySelector('.nav-dropdown');
        if (existingDropdown && !e.target.closest('.skill-tag')) {
            existingDropdown.remove();
        }
    });

    // B. Handle clicks on Skill Tags
    document.body.addEventListener('click', (e) => {
        if (e.target.classList.contains('skill-tag')) {
            e.preventDefault();
            e.stopPropagation();
            
            // 1. Clean up old dropdowns
            const existing = document.querySelector('.nav-dropdown');
            if (existing) existing.remove();

            // 2. Get Data
            const btn = e.target;
            const targetIds = btn.dataset.targets ? btn.dataset.targets.split(',') : [];
            const originId = btn.dataset.origin;

            // 3. Filter targets
            // Don't show the section we are currently in
            let validTargets = targetIds.filter(id => id !== originId);

            // ---------------------------------------------------------
            // UX FIX: If we are inside a Job/School (not summary), 
            // ALWAYS offer a link back to the main Skills Summary.
            // ---------------------------------------------------------
            const summaryId = 'skills-list'; // The ID generated by utils.js for the list container
            if (originId !== 'summary' && originId !== summaryId) {
                // Add summary to the end of the list
                validTargets.push(summaryId);
            }

            // If STILL nowhere to go (e.g. clicked in summary and unique to summary), stop.
            if (validTargets.length === 0) return;

            // 4. Create Dropdown HTML
            const dropdown = document.createElement('div');
            dropdown.className = 'nav-dropdown';
            
            const header = document.createElement('div');
            header.className = 'nav-dropdown-header';
            
            const isTr = document.documentElement.lang === 'tr';
            header.innerText = isTr ? "Bağlantılar:" : "Connections:";
            dropdown.appendChild(header);

            validTargets.forEach(id => {
                const targetEl = document.getElementById(id);
                if (targetEl) {
                    let role, context;

                    // SPECIAL CASE: Link back to Summary
                    if (id === summaryId) {
                        role = isTr ? "Yetkinlik Özeti" : "Skills Summary";
                        context = isTr ? "Kategoriyi Görüntüle" : "View Category";
                    } else {
                        // Standard Job/Edu Block
                        role = targetEl.querySelector('.job-title')?.innerText || "Unknown Role";
                        context = targetEl.querySelector('.company')?.innerText || "";
                    }

                    const item = document.createElement('button');
                    item.className = 'nav-item';
                    item.innerHTML = `
                        ${role}
                        <span class="nav-context">${context}</span>
                    `;
                    
                    item.onclick = () => {
                        targetEl.scrollIntoView({ behavior: 'smooth', block: 'center' });
                        
                        // Highlight Flash Effect
                        const originalTransition = targetEl.style.transition;
                        targetEl.style.transition = "background-color 0.5s ease";
                        targetEl.style.backgroundColor = "rgba(108, 92, 231, 0.1)"; 
                        
                        setTimeout(() => { 
                            targetEl.style.backgroundColor = "var(--card-bg)"; // Reset
                            setTimeout(() => { targetEl.style.transition = originalTransition; }, 500);
                        }, 800);
                        
                        dropdown.remove();
                    };
                    
                    dropdown.appendChild(item);
                }
            });

            // 5. Position Dropdown
            document.body.appendChild(dropdown);
            const rect = btn.getBoundingClientRect();
            const scrollTop = window.pageYOffset || document.documentElement.scrollTop;
            const scrollLeft = window.pageXOffset || document.documentElement.scrollLeft;
            
            dropdown.style.top = `${rect.bottom + scrollTop + 6}px`;
            dropdown.style.left = `${rect.left + scrollLeft}px`;
            
            // Edge detection
            const dropdownRect = dropdown.getBoundingClientRect();
            if (dropdownRect.right > window.innerWidth) {
                dropdown.style.left = 'auto';
                dropdown.style.right = '20px';
            }
        }
    });
}

// --- 4. EVENTS & INITIALIZATION ---
document.addEventListener('DOMContentLoaded', () => {
    // Detect language from storage or browser settings
    const savedLang = localStorage.getItem('preferredLang');
    const browserLang = (navigator.language || navigator.userLanguage).startsWith('tr') ? 'tr' : 'en';
    let currentLang = savedLang || browserLang;

    // Initial Render
    renderResume(currentLang);
    
    // Initialize Navigation Logic
    setupSkillNavigation();

    // Language Toggles
    document.getElementById('btn-tr').addEventListener('click', () => {
        localStorage.setItem('preferredLang', 'tr');
        renderResume('tr');
    });

    document.getElementById('btn-en').addEventListener('click', () => {
        localStorage.setItem('preferredLang', 'en');
        renderResume('en');
    });

    // Print functionality
    const btnPrint = document.getElementById('btn-print');
    if (btnPrint) btnPrint.addEventListener('click', () => window.print());

    // Theme Toggle (Dark/Light Mode)
    const btnTheme = document.getElementById('btn-theme');
    const htmlElement = document.documentElement;
    if (btnTheme) {
        btnTheme.addEventListener('click', () => {
            if (htmlElement.getAttribute('data-theme') === 'dark') {
                htmlElement.removeAttribute('data-theme');
                localStorage.setItem('theme-preference', 'light');
            } else {
                htmlElement.setAttribute('data-theme', 'dark');
                localStorage.setItem('theme-preference', 'dark');
            }
        });
    }

    // Email Copy to Clipboard Logic
    const mailLink = document.getElementById('link-email');
    if (mailLink) {
        mailLink.addEventListener('click', (e) => {
            e.preventDefault();
            const emailText = resumeData.meta.email;
            const isTr = document.documentElement.lang === 'tr';
            
            navigator.clipboard.writeText(emailText).then(() => {
                mailLink.setAttribute('data-copy-text', isTr ? "Kopyalandı!" : "Copied!");
                mailLink.classList.add('copied');
                setTimeout(() => { mailLink.classList.remove('copied'); }, 2000);
            });
        });
    }
});
